logo:
  title: '浙临天路客'
  subtitle: "Zhejiang Lin'an Koinonia of Pilgrims"
menubar:
  columns: 4 # 一行多少个
  items: # 可按照自己需求增加，符合以下格式即可
     - id: post # 页面中高亮的 menu_id
       theme: '#1BCDFC' # 高亮时的颜色，仅 svg 中 fill="currentColor" 时有效
       icon: default:documents
       title: 博客 # 标题
       url: /
     - id: wiki
       theme: '#3DC550'
       icon: default:category
       title: 文档
       url: /docmost
     - id: explore
       theme: '#FA6400'
       icon: default:pin
       title: 探索
       url: /notes/
     - id: social
       theme: '#F44336'
       icon: default:hashtag
       title: 社交
       url: /friends/
